apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: self-hpa
  namespace: self
spec:
  scaleTargetRef:
    kind: Deployment
    name: self-deployment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5 # Corrected value
